//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Diagnostics
{
    using System;
    
    
    public class Newtb
    {
        
        private int id;
        
        private string rowid;
        
        private string attri;
        
        private string val;
        
        // 
        public int Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }
        
        // 
        public string Rowid
        {
            get
            {
                return this.rowid;
            }
            set
            {
                this.rowid = value;
            }
        }
        
        // 
        public string Attri
        {
            get
            {
                return this.attri;
            }
            set
            {
                this.attri = value;
            }
        }
        
        // 
        public string Val
        {
            get
            {
                return this.val;
            }
            set
            {
                this.val = value;
            }
        }
    }
}
