//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Diagnostics
{
    using System;
    
    
    public class Tab
    {
        
        private int n;
        
        // 
        public int N
        {
            get
            {
                return this.n;
            }
            set
            {
                this.n = value;
            }
        }
    }
}
