//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Diagnostics
{
    using System;
    
    
    public class Test_table
    {
        
        private int emp_no;
        
        private string ename;
        
        private string job;
        
        private int manager_no;
        
        // 
        public int Emp_no
        {
            get
            {
                return this.emp_no;
            }
            set
            {
                this.emp_no = value;
            }
        }
        
        // 
        public string Ename
        {
            get
            {
                return this.ename;
            }
            set
            {
                this.ename = value;
            }
        }
        
        // 
        public string Job
        {
            get
            {
                return this.job;
            }
            set
            {
                this.job = value;
            }
        }
        
        // 
        public int Manager_no
        {
            get
            {
                return this.manager_no;
            }
            set
            {
                this.manager_no = value;
            }
        }
    }
}
